#!/bin/bash
#This shell_script must be executable, if not do a chmod
#$1 is the path with the data unzip 
#$2 is the path to ancillary data mounted in the docker run command
	destiny=/results
	name=$(basename $1)
	basename=$(echo $name|sed -n 's/\(L*.*\)/\1/;p')
	dir=$destiny/$basename
	year=$(echo $name|sed -nE 's/L[A-Z][5-7][0-9]{3}[0-9]{3}([0-9]{4}).*/\1/p')
	#dir_ledaps=/opt/ledaps
	cp $2/CMGDEM.hdf $dir
	mkdir $dir/EP_TOMS && cp -r $2/EP_TOMS/ozone_$year $dir/EP_TOMS
	mkdir $dir/REANALYSIS && cp -r $2/REANALYSIS/RE_$year $dir/REANALYSIS
	cd $dir 
	metadata=$(ls $dir|grep -E ^L[A-Z]?[5-7][0-9]{3}[0-9]{3}.*_MTL.txt)
	metadataxml=$(echo $metadata|sed -nE 's/(L.*).txt/\1.xml/p')
	export LEDAPS_AUX_DIR=$(pwd)
	cd $dir && $BIN/convert_lpgs_to_espa --mtl=$metadata --xml=$metadataxml
	cd $dir && $BIN/do_ledaps.csh $metadataxml
	cd $dir && $BIN/convert_espa_to_gtif --xml=$metadataxml --gtif=lndsr.$basename.tif 
	cd $dir && $BIN/convert_espa_to_hdf --xml=$metadataxml --hdf=lndsr.$basename.hdf
	rm -r $dir/CMGDEM.hdf
	rm -r $dir/EP_TOMS/
	rm -r $dir/REANALYSIS/
