#!/bin/bash
#This shell_script must be executable, if not do a chmod
#$1 is the path with the data unzip
#$2 is the path to ancillary data mounted in the docker run command
	destiny=/results
	name=$(basename $1)
	basename=$(echo $name|sed -n 's/\(L*.*\)/\1/;p')
	dir=$destiny/$basename
	year=$(echo $name|sed -nE 's/L[A-Z][5-7][0-9]{3}[0-9]{3}([0-9]{4}).*/\1/p')
	mkdir -p $dir
	#dir_ledaps=/opt/ledaps
	cp $2/CMGDEM.hdf $dir
	mkdir -p $dir/EP_TOMS && cp -r $2/EP_TOMS/ozone_$year $dir/EP_TOMS
	mkdir -p $dir/REANALYSIS && cp -r $2/REANALYSIS/RE_$year $dir/REANALYSIS
	cd $dir
	cp $1/* .
	metadata=$(ls $dir|grep -E ^L[A-Z]?[5-7][0-9]{3}[0-9]{3}.*_MTL.txt)
	cd $dir && $BIN/do_ledaps.csh $metadata
	rm -r $dir/CMGDEM.hdf
	rm -r $dir/EP_TOMS/
	rm -r $dir/REANALYSIS/
