#!/bin/bash
#This shell_script must be executable, if not do a chmod
#$1 is the path with the data unzip
#$2 is the path to ancillary data mounted in the docker run command


#Ask for confirmation
read -p "Long running process... Are you sure, you want to execute this on $1? It might take a while. (y/n) " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

	destiny=/results
	name=$(basename $1)
	basename=$(echo $name|sed -n 's/\(L*.*\)/\1/;p')
	dir=$destiny/$basename
	year=$(echo $name|sed -nE 's/L[A-Z][4-7][0-9]{3}[0-9]{3}([0-9]{4}).*/\1/p')
	mkdir -p $dir

	dir_ledaps=/opt/ledaps
	cp $2/CMGDEM.hdf $dir
	cp $2/L5_TM/gold.dat $dir
	cp $2/L5_TM/gnew.dat $dir
	cp $2/L5_TM/gold_2003.dat $dir
	mkdir -p $dir/EP_TOMS && cp -r $2/EP_TOMS/ozone_$year $dir/EP_TOMS
	mkdir -p $dir/REANALYSIS && cp -r $2/REANALYSIS/RE_$year $dir/REANALYSIS
	cd $dir
	cp $1/* .

	metadata=$(ls $dir|grep -E ^L[A-Z]?[4-7][0-9]{3}[0-9]{3}.*_MTL.txt)
	metadataxml=$(echo $metadata|sed -nE 's/(L.*)_MTL.txt/\1.xml/p')

	# export LEDAPS_AUX_DIR=$(pwd)
	cd $dir && $BIN/convert_lpgs_to_espa --mtl=$metadata #--xml=$metadataxml

	# actual ledaps process
	cd $dir && $BIN/do_ledaps.csh $metadataxml

	# output in different formats (uncomment if not needed)
	cd $dir && $BIN/convert_espa_to_gtif --xml=$metadataxml --gtif=lndsr.$basename.tif
	cd $dir && $BIN/convert_espa_to_hdf --xml=$metadataxml --hdf=lndsr.$basename.hdf
	# TODO: gdal_translate lndsr.$basename.tif $basename.sr.geotiff

	# cleaning up
	cd $dir
	rm -r $dir/CMGDEM.hdf
	rm -r $dir/EP_TOMS/
	rm -r $dir/REANALYSIS/

fi
