#!/bin/bash
#This shell_script must be executable, if not do a chmod
name=$(basename $2)
basename=$(echo $name|sed -n 's/\(L*.*\).tar.bz/\1/;p')
dir=$3/$basename
mkdir $dir
cp $2 $dir
cd $dir && tar xvf $name
metadata=$(ls $dir|grep -E ^L[A-Z]?[5-8][0-9]{3}[0-9]{3}.*_MTL.txt)
metadataxml=$(echo $metadata|sed -nE 's/(L.*).txt/\1.xml/p')
#file_fused=
$BIN/convert_lpgs_to_espa --mtl=$metadata --xml=$metadataxml
$BIN/create_land_water_mask --xml=$metadataxml
#$BIN/l8_sr --xml=$metadataxml --aux=$file_fused --verbose --write_toa
$BIN/do_l8_sr.py --xml=$metadataxml