#!/bin/bash
#This shell_script must be executable, if not do a chmod
#$1 is the path with the data unzip
destiny=/results
name=$(basename $1)
basename=$(echo $name|sed -n 's/\(L*.*\)/\1/;p')
dir=$destiny/$basename
cd $dir
metadata=$(ls $dir|grep -E ^L[A-Z]?[5-8][0-9]{3}[0-9]{3}.*_MTL.txt)
metadataxml=$(echo $metadata|sed -nE 's/(L.*).txt/\1.xml/p')
echo $metadataxml
$BIN/convert_lpgs_to_espa --mtl=$metadata --xml=$metadataxml
#$BIN/create_land_water_mask --xml=$metadataxml
#$BIN/lacsr --xml=LC80210482013105LGN01_MTL.xml --aux=L8ANC2013105.hdf_fused --verbose --write_toa
$BIN/do_lacsr.py --xml=$metadataxml
$BIN/convert_espa_to_hdf --xml=$metadataxml --hdf=lndsr.$basename.hdf --del_src_files
#rm $dir/$name
